// AutoLoc/Project_Files/RMI/Source_Code_Samples/vue/product/ranking/components/ListItem.vue
<template>
  <li>
    <a :href="linkPath" class="product-ranking-Card c-Card_Normal">
      <div class="product-ranking-Card_Img">
        <div class="product-ranking-Card_Label">
          <span v-if="isNew">NEW</span>
        </div>

        <figure>
          <img
            :src="imgPath"
            alt=""
            width="160"
          >
        </figure>
      </div>

      <div class="product-ranking-Card_Data">
        <div class="product-ranking-Card_Data-label">
          <RankLabel :ranking="deviceThisMonth(selectDeviceName)" />
          <RankTrend
            v-if="isTrend"
            :rankingThisMonth="deviceThisMonth(selectDeviceName)"
            :rankingLastMonth="deviceLastMonth(selectDeviceName)"
          />

        </div>
        <!-- For debug
        <p>先月{{ summary['rank-last-month'] }}位</p>
        <p>今月{{ summary['rank-this-month'] }}位</p>
        <p class="c-Txt_Emp-02">先月{{ summary['rank-add-last-month'] }}位</p>
        <p class="c-Txt_Emp-02">今月{{ summary['rank-add-this-month'] }}位</p>
        -->

        <h2 class="c-Heading_Lv2 u-Adjust_Mt-8">{{ summary.product }}</h2>
        <div class="product-ranking-Card_Data-sub">
          <div>{{ summary.manufacturer }}</div>
          <div class="u-Adjust_Ml-16 c-Txt_Cap">発売日:{{ displayRereaseDate }}</div>
        </div>

        <div class="product-ranking-Card_Data-price">
          <!-- Appleの場合 -->
          <template v-if="isApple">


            <dl class="product-ranking-Card_Data-price-item">
              <dt>48回払い（税込）</dt>
              <dd class="c-Txt_Emp-01">月々<span class="product-ranking-Card_Price-num">{{ displayPayment48 }}</span>円～</dd>
            </dl>
            <p
              v-if="isPayment48Note"
              class="product-ranking-Card_Data-price-item-cap"
            >
              {{ summary['payment48-text'] }}{{ summary['ranking-iphone-note1'] }}
            </p>

            <dl class="product-ranking-Card_Data-price-item">
              <dt>一括払い（税込）</dt>
              <dd v-if="isDiscount">
                <del>
                  {{ displayDiscount }}
                </del>円～<span v-if="isDiscountpriceCap">{{ summary['double-price-txt'] }}</span>→
                <span class="c-Txt_Normal c-Txt_Emp-01">{{ displayPayment1 }}</span>
                円～
              </dd>
              <dd v-else><span class="c-Txt_Normal c-Txt_Emp-01">{{ displayPayment1 }}</span>円～</dd>

            </dl>
          </template>

          <!-- Rakutenオリジナル・Androidの場合 -->
          <template v-else>
            <template v-if="!summary['replacement-flag'] && summary['product'] !== 'Rakuten Hand 5G'">
              <dl class="product-ranking-Card_Data-price-item">
                <dt>48回払い（税込）</dt>
                <dd class="c-Txt_Emp-01">月々<span class="product-ranking-Card_Price-num">{{ displayPaymentPrice }}</span>円</dd>
              </dl>
              <p class="product-ranking-Card_Data-price-item-cap">
                {{ summary['ranking-payment48-text'] }}{{ summary['ranking-payment48-note'] }}
              </p>
              <dl class="product-ranking-Card_Data-price-item">
                <dt>一括払い（税込）</dt>
                <dd v-if="summary['strikethrough']">
                <dd v-if="isDiscount">
                  <span class="c-Txt_Normal c-Txt_Emp-01">{{ displayPrice }}</span>
                  円
                </dd>
                <dd v-else><span class="c-Txt_Normal c-Txt_Emp-01">{{ displayPrice }}</span>円</dd>
              </dl>
            </template>
            <template v-else>
              <dl class="product-ranking-Card_Data-price-item">
              <dt>製品価格（税込）</dt>
              <dd class="c-Txt_Emp-01">
                <span v-if="isCancellation" class="c-Txt_Normal-s" style="font-weight: 400;">
                <span style="text-decoration: line-through;">{{ displayCancellationPrice }}円</span>
                <span v-if="isOppoReno7">※</span><span v-if="isGalaxyA235G">※</span><span v-if="isRedmiNote11Pro5G">※</span>→
                </span>
                <span class="product-ranking-Card_Price-num">{{ displayPrice }}</span>円
              </dd>
              </dl>
            </template>

            <DiscountListItem
              v-if="isDiscountprice"
              :discountPrice="dispkaydiscountPrice"
              :rankingDiscountNote="summary['ranking-discount-note']"
              :mnp="summary.mnp"
            />

            <PointBackListItem
              v-if="isPointBack1"
              :point="displayPointBackPoint1"
              :preText="summary['pointback-pre-text1']"
              :postText="summary['pointback-post-text1']"
              :note="summary['ranking-note1']"
            />

            <!-- <PointBackListItem
              v-if="isPointBack2"
              :point="displayPointBackPoint2"
              :preText="summary['pointback-pre-text2']"
              :postText="summary['pointback-post-text2']"
              :note="summary['ranking-note2']"
            /> -->
          </template>

          <div class="product-ranking-Card_Data-price-result">
            <!-- Appleの場合(計算結果) -->
            <div
              v-if="isApple"
              class="c-Txt_Emp-02"
            >
              {{ summary['top-carousel-iphone-pre-text'] }}
            {{ summary['top-carousel-iphone-pre-text2'] }}{{ summary['top-carousel-pointback-txt2'] }}<span class="product-ranking-Card_Price-num">{{ displayPointBackPointIphone }}</span>{{ summary['ranking-pointback-text3'] }}{{ summary['ranking-iphone-note2'] }}
            </div>

            <!-- Rakutenオリジナル・Androidの場合(計算結果) -->
            <div
              v-else
              class="c-Txt_Normal-s c-Txt_Emp-02"
            >
              <template v-if="!summary['replacement-flag'] && summary['product'] !== 'Rakuten Hand 5G' && summary['product'] !== 'Galaxy A23 5G' && summary['product'] !== 'AQUOS wish3' && summary['product'] !== 'Xperia 10 V' && summary['product'] !== 'OPPO Reno9 A' && summary['product'] !== 'AQUOS sense8'">
                {{ summary['ranking-pointback-text1'] }}{{ summary['ranking-pointback-text2'] }}<span class="product-ranking-Card_Price-num">{{ displayCancellationPrice }}</span>{{ summary['ranking-pointback-text3'] }}{{ summary['ranking-iphone-note2'] }}
              </template>
              <template v-else>
                <template v-if="summary['product'] === 'Rakuten Hand 5G'">
                  <span class="product-ranking-Card_Price-num">{{ displayResultPrice }}</span>円
                </template>
                <template v-else>
                  <template v-if="summary['product'] === 'Galaxy A23 5G' || summary['product'] === 'AQUOS wish3' || summary['product'] === 'Xperia 10 V' || summary['product'] === 'OPPO Reno9 A' || summary['product'] === 'AQUOS sense8'">
                  値引き後価格<span class="product-ranking-Card_Price-num">{{ displayResultPrice }}</span>円
                  </template>
                  <template v-else>
                    実質<span class="product-ranking-Card_Price-num">{{ displayResultPrice }}</span>円
                  </template>
                </template>
              </template>
            </div>
            <!-- <div
              v-if="isPointBack3"
              class="c-Txt_Normal-s c-Txt_Emp-02"
            >
              {{ summary['pointback-pre-text3'] }}<span class="product-ranking-Card_Price-num">{{ displayPointBackPoint3 }}</span>ポイント{{ summary['pointback-post-text3'] }}{{ summary['ranking-note3'] }}
            </div> -->
          </div>
        </div>
      </div>

      <div class="product-ranking-Card_Feature">
        <h4 class="c-Heading_Lv4">特長</h4>

        <ul class="c-List_Text-disc">
          <li class="u-Adjust_Mt-8" v-html="displayFeature1"></li>
          <li class="u-Adjust_Mt-8" v-html="displayFeature2"></li>
          <li class="u-Adjust_Mt-8" v-html="displayFeature3"></li>
        </ul>

        <div class="u-Adjust_Mt-16">
          <p
            v-for="(note, i) in noteList"
            :key="i"
            class="c-Txt_Cap"
          >
            {{ note.trim() }}
          </p>
        </div>
      </div>
    </a>
  </li>
</template>

<script>
import PointBackListItem from './PointBackListItem.vue';
import RankLabel from './RankLabel.vue';
import RankTrend from './RankTrend.vue';
import DiscountListItem from './DiscountListItem.vue';


export default {
  components: {
    PointBackListItem,
    RankLabel,
    RankTrend,
    DiscountListItem
  },
  name: 'ListItem',
  props: [ 'summary', 'selectDeviceName' ],
  data() {
    return {
      isNew: false,
      isTrend: true,
      path: {
        sitepath: '/',
        rootpath: '/',
        onboardingpath: 'https://onboarding.mobile.rakuten.co.jp/',
      },
    }
  },
  methods: {
    brInlistTransform(text) {
      if (/\n/.test(text)) {
        const textList = text
          .trim()
          .split('\n')
          .map(textItem => this.noteInlistTransform(textItem));

        return textList.join('<br>')
      } else {
        return this.noteInlistTransform(text.trim())
      }
    },
    noteInlistTransform(text) {
      const trimText = text.trim();

      if (/^※/.test(trimText)) {
        return `<span class="c-Txt_Cap u-Adjust_Ml-0" style="display: block";>${trimText}</span>`
      } else {
        return trimText.replace('※', '<small>※</small>')
      }
    },
    deviceThisMonth(selectDeviceName) {
        return ( selectDeviceName === 'both') ? this.summary['rank-this-month'] : this.summary['rank-add-this-month'];
    },
    deviceLastMonth(selectDeviceName) {
        return ( selectDeviceName === 'both') ? this.summary['rank-last-month'] : this.summary['rank-add-last-month'];
    }
  },
  computed: {
    isApple() {
      return this.summary.manufacturer && this.summary.manufacturer.trim() === 'Apple'
    },
    isRakuten() {
      return this.summary.manufacturer && this.summary.manufacturer.trim() === 'Rakuten Mobile'
    },
    isPointBack1() {
      return this.summary.point1 && this.summary.point1.trim() !== ''
    },
    // isPointBack2() {
    //   return this.summary.point2 && this.summary.point2.trim() !== ''
    // },
    // isPointBack3() {
    //   return this.summary.point3 && this.summary.point3.trim() !== ''
    // },
    isCancellation() {
      return this.summary.strikethrough && this.summary.strikethrough.trim() !== ''
    },
    isOppoReno7() {
      return this.summary.product.trim() === 'OPPO Reno7 A'
    },
    isRedmiNote11Pro5G(){
        return this.summary.product.trim() === 'Redmi Note 11 Pro 5G'
    },
    isGalaxyA235G() {
      return this.summary.product.trim() === 'Galaxy A23 5G'
    },
    isAQUOSsense6s() {
        return this.summary.product.trim() === 'AQUOS sense6s'
    },
    isPayment48Note() {
      return this.summary['payment48-text'] && this.summary['payment48-text'].trim() !== ''
    },
    isDiscount() {
      // MEMO: csv入稿の際に、discount_textがない場合があるので注意(23年1月27時点でiphone 14が該当しており、ロジックを修正)
      return  this.summary['discount_text'] !== '' || this.summary['discount'] !== ''
    },
    isDiscountprice() {
      return this.summary.discountprice && this.summary.discountprice.trim() !== ''
    },
    isDiscountpriceCap() {
      return this.summary['double-price-txt'] && this.summary['double-price-txt'].trim() !== ''
    },
    displayRereaseDate() {
      const splitDate = this.summary.release.split('/');
      return `${splitDate[0]}年${splitDate[1]}月${splitDate[2]}日`
    },
    displayPayment48() {
      return (+this.summary.payment48).toLocaleString()
    },
    displayPayment1() {
      return (+this.summary.payment1).toLocaleString()
    },

    displayPointBackPoint1() {
      return (+this.summary.point1).toLocaleString()
    },
    displayPointBackPoint2() {
      return (+this.summary.point2).toLocaleString()
    },
    displayPointBackPoint3() {
      return (+this.summary.point3).toLocaleString()
    },
    displayPointBackPointIphone() {
      return (+this.summary['top-carousel-pointback-num']).toLocaleString()
    },
    dispkaydiscountPrice() {
      return (+this.summary.discountprice).toLocaleString()
    },
    displayPrice() {
      return (+this.summary.price2).toLocaleString()
    },
    displayPaymentPrice() {
      return (+this.summary.price4).toLocaleString()
    },
    displayPointTotal() {
      return (+this.summary.price4).toLocaleString()
    },
    displayCancellationPrice() {
      return (+this.summary.pointtotal).toLocaleString()
    },
    displayResultPrice() {
      const originalPrice = this.summary.price2 || 0;
      const point1 = this.summary.point1 || 0;
      const point2 = this.summary.point2 || 0;
      const discountprice = this.summary.discountprice || 0;

      const resultPrice = originalPrice - point1 - point2 - discountprice;
      return resultPrice > 0 ? resultPrice.toLocaleString() : '0'
    },
    displayDiscount() {
      console.log(+this.summary.discount)
      return (+this.summary.discount).toLocaleString()
    },
    displayStrikethroughPrice() {
      return (+this.summary.strikethrough).toLocaleString()
    },

    displayFeature1() {
      return this.brInlistTransform(this.summary.feature1)
    },
    displayFeature2() {
      return this.brInlistTransform(this.summary.feature2)
    },
    displayFeature3() {
      return this.brInlistTransform(this.summary.feature3)
    },

    noteList() {
      return this.summary.note.split('\n')
    },

    imgPath() {
      const iphoneImgName = this.summary.directory.split('-').join('').trim();
      const param = this.summary.update && this.summary.update.trim() !== '' ? `?${this.summary.update.trim()}` : '';

      return this.isApple
        ? `${this.path.sitepath}assets/img/product/iphone/top/thumb-product-iphone-top-${iphoneImgName}.png${param}`
        : `${this.path.sitepath}assets/img/product/${this.summary.directory.trim()}/pht-device-thumb.png${param}`
    },
    linkPath() {
      return this.isApple
        ? `${this.path.sitepath}product/iphone/${this.summary.directory.trim()}/?l-id=product_ranking_iphone_${this.summary.directory.trim()}`
        : this.isRakuten
        ? `${this.path.sitepath}product/smartphone/${this.summary.directory.trim()}/?l-id=product_ranking_rakuten_${this.summary.directory.trim()}`
        : `${this.path.sitepath}product/smartphone/${this.summary.directory.trim()}/?l-id=product_ranking_smartphone_${this.summary.directory.trim()}`
    },
  },
  created() {
        if (this.summary['rank-last-month'].trim() === '') {
            this.isNew = true
            this.isTrend = false
        } else {
            this.isNew = false
            this.isTrend = true
        }
  },
  updated() {
        // 新規ランクイン製品のセットアップ
        if ( this.selectDeviceName === 'Android' || this.selectDeviceName === 'iPhone' ) {
            console.log('Android');
            if (this.summary['rank-add-last-month'].trim() === '') {
                this.isNew = true
                this.isTrend = false
            } else {
                this.isNew = false
                this.isTrend = true
            }
        } else {
            console.log('総合');
            if (this.summary['rank-last-month'].trim() === '') {
                this.isNew = true
                this.isTrend = false
            } else {
                this.isNew = false
                this.isTrend = true
            }
        }
    },
    isCpnSubject() {
        const cpnSubject = ['iPhone 13 Pro Max', 'iPhone 13 Pro', 'iPhone 13', 'iPhone 13 mini', 'iPhone SE（第3世代）', 'iPhone 12', 'iPhone 12 mini']
        for( let i = 0; i < cpnSubject.length; i++ ) {
            if( this.summary.product == cpnSubject[i] ) {
                return true;
            }
        }
    }
}
</script>

// AutoLoc/Project_Files/RMI/Source_Code_Samples/components/fragment/product/ranking/ListItem.tsx
import React, { useEffect } from 'react'
import styled from 'styled-components'
import Utils from '@styles/Utils.module.scss'
import { Heading } from '@components/atoms/Heading'
import {
  TxtCap,
  TxtEmp02,
  TxtEmp01,
  TxtSize,
  TxtNormal,
} from '@components/atoms/Txt'
import { CardNormal } from '@components/atoms/Card'
import { UlOnly } from '@components/atoms/List'
import { mixins } from '@components/utils/Mixins'
import { IconArrowUp, IconArrowDown, IconArrowRight } from '@components/icons'
import { fontRakutenSans } from '@styles/fonts'

const CardCustom = styled(CardNormal)`
  ${mixins.mq.MinL} {
    display: flex;
  }
`
const CardImg = styled.div`
  text-align: center;
  ${mixins.mq.MinL} {
    width: 160px;
  }
`
const CardLabel = styled.div`
  size: 20px;
  weight: 400;
  font-family: ${fontRakutenSans.style.fontFamily}, var(--noto-sans-jp),
    sans-serif;
  color: #ff008c;
  font-weight: bold;
`
const CardData = styled.div`
  margin-top: 16px;

  ${mixins.mq.MinL} {
    width: 296px;
    margin-top: 0;
    margin-left: 24px;
  }

  .label {
    display: flex;
    justify-content: flex-start;
    align-items: center;

    > div:first-of-type {
      margin-right: 8px;
    }
  }

  .price {
    margin-top: 20px;
    font-size: 13px;

    > dl + dl {
      margin-top: 4px;
    }

    .item {
      display: flex;
      justify-content: space-between;
      align-items: baseline;

      > dt {
        flex: 0 1 auto;
      }

      > dd {
        flex: 1 0 auto;
        text-align: right;
      }
    }
    .cap {
      font-size: 10px;
      + .item {
        margin-top: 10px;
      }
    }

    .result {
      text-align: right;
      margin-top: 8px;
      padding-top: 8px;
      border-top: 1px solid ${props => props.theme.colors.monotone75};
    }
  }

  .sub {
    font-size: 13px;
    margin-top: 8px;
    display: flex;
    justify-content: flex-start;
    align-items: baseline;
  }
`
const PriceNum = styled.span`
  font-size: 20px;
  font-weight: bold;
  font-family: ${fontRakutenSans.style.fontFamily}, var(--noto-sans-jp),
    sans-serif;
`
const CardFeature = styled.div`
  margin-top: 16px;
  ${mixins.mq.MinL} {
    width: calc(100% - (160px + 296px + 24px + 80px));
    margin-top: 0;
    margin-left: 80px;
  }
`
const TxtSizeWeightNormal = styled(TxtSize)`
  font-weight: normal;
`
const Rank = styled.div`
  color: ${props => props.theme.colors.white};
  padding: 0 8px;

  > span {
    margin-left: 4px;
    font-size: 20px;
    font-family: ${fontRakutenSans.style.fontFamily}, var(--noto-sans-jp),
      sans-serif;
    font-weight: bold;
    transform: translateY(1px);
    display: inline-block;
  }

  svg {
    transform: translateY(2px);
  }
  &.rank-1 {
    background-color: #ccbb1d;
  }
  &.rank-2 {
    background-color: ${props => props.theme.colors.monotone75};
  }
  &.rank-3 {
    background-color: #ca8a37;
  }
  &.rank-other {
    background: ${props => props.theme.colors.monotone93};
    color: ${props => props.theme.colors.lightBlack};

    svg path {
      fill: ${props => props.theme.colors.lightBlack};
    }
  }
`
const Trend = styled.div`
  font-size: 13px;
  font-weight: bold;
  > span {
    font-size: 14px;
    font-weight: normal;
    margin-right: 4px;
  }
`

interface ListItemProps {
  device: { [key: string]: string }
}
export const ListItem = (props: ListItemProps) => {
  const { device } = props
  const isApple = () => {
    return device.manufacturer && device.manufacturer.trim() === 'Apple'
  }
  const isRakuten = () => {
    return (
      device.manufacturer && device.manufacturer.trim() === 'Rakuten Mobile'
    )
  }
  const linkPath = () => {
    return isApple()
      ? `/product/iphone/${device.directory.trim()}/?l-id=product_ranking_iphone_${device.directory.trim()}`
      : isRakuten()
      ? `/product/smartphone/${device.directory.trim()}/?l-id=product_ranking_rakuten_${device.directory.trim()}`
      : `/product/smartphone/${device.directory.trim()}/?l-id=product_ranking_smartphone_${device.directory.trim()}`
  }
  const isNew = () => {
    return device['rank-last-month'].trim() === '' ? true : false
  }
  const imgPath = () => {
    const iphoneImgName = device.directory.split('-').join('').trim()
    const param =
      device.update && device.update.trim() !== ''
        ? `?${device.update.trim()}`
        : ''

    return isApple()
      ? `/img/product/iphone/top/thumb-${iphoneImgName}.png${param}`
      : `/img/product/${device.directory.trim()}/pht-device-01.png${param}`
  }
  const displayRereaseDate = () => {
    const splitDate = device.release.split('/')
    return `${splitDate[0]}年${splitDate[1]}月${splitDate[2]}日`
  }
  const displayPayment48 = () => {
    return (+device.payment48).toLocaleString()
  }
  const isPayment48Note = () => {
    return device['payment48-text'] && device['payment48-text'].trim() !== ''
  }
  const isDiscount = () => {
    return device['discount_text'] !== '' && device['discount'] !== ''
  }
  const displayPayment1 = () => {
    return (+device.payment1).toLocaleString()
  }
  const displayDiscount = () => {
    return (+device.discount).toLocaleString()
  }
  const isCancellation = () => {
    return device.strikethrough && device.strikethrough.trim() !== ''
  }
  const displayPrice = () => {
    return (+device.price2).toLocaleString()
  }
  const displayCancellationPrice = () => {
    return (+device.strikethrough).toLocaleString()
  }
  const displayPointBackPointIphone = () => {
    return (+device['top-carousel-pointback-num']).toLocaleString()
  }
  const displayResultPrice = () => {
    const originalPrice = parseInt(device.price2, 10) || 0
    const point1 = parseInt(device.point1, 10) || 0
    const point2 = parseInt(device.point2, 10) || 0

    const resultPrice = originalPrice - point1 - point2
    return resultPrice > 0 ? resultPrice.toLocaleString() : '0'
  }
  const isPointBack3 = () => {
    return device.point3 && device.point3.trim() !== ''
  }
  const noteList = () => {
    return device.note.split('\n')
  }
  const isPointBack1 = () => {
    return device.point1 && device.point1.trim() !== ''
  }
  const isPointBack2 = () => {
    return device.point2 && device.point2.trim() !== ''
  }
  const displayPointBackPoint1 = () => {
    return (+device.point1).toLocaleString()
  }
  const displayPointBackPoint2 = () => {
    return (+device.point2).toLocaleString()
  }
  const displayPointBackPoint3 = () => {
    return (+device.point3).toLocaleString()
  }
  const rankLabelClass = () => {
    const rankingNum = /^[1-3]$/.test(device['rank-this-month'])
      ? device['rank-this-month']
      : 'other'

    return 'rank-' + rankingNum
  }
  const trendClass = () => {
    const ns = 'rank-'
    return +device['rank-this-month'] < +device['rank-last-month']
      ? ns + 'up'
      : +device['rank-this-month'] > +device['rank-last-month']
      ? ns + 'down'
      : ns + 'stay'
  }
  const trendText = () => {
    return +device['rank-this-month'] < +device['rank-last-month']
      ? 'UP'
      : +device['rank-this-month'] > +device['rank-last-month']
      ? 'Down'
      : 'Stay'
  }
  const brInlistTransform = (text: string) => {
    if (/\n/.test(text)) {
      const textList = text
        .trim()
        .split('\n')
        .map((elem, i) => {
          const trimText = text.trim()
          if (/^※/.test(trimText)) {
            return (
              <TxtCap
                key={i}
                className={Utils['Ml-0']}
                style={{ display: 'block' }}
              >
                {trimText}
              </TxtCap>
            )
          } else {
            const resultArr = trimText.split('※')
            return resultArr.map((elemC, i) => {
              if (i === 0) {
                return <React.Fragment key={i}>{elemC}</React.Fragment>
              } else {
                return (
                  <React.Fragment key={i}>
                    <small>※</small>
                    {elemC}
                  </React.Fragment>
                )
              }
            })
          }
        })

      return textList.map((elem, i, arr) => {
        if (i !== arr.length - 1) {
          return (
            <React.Fragment key={i}>
              {elem}
              <br />
            </React.Fragment>
          )
        } else {
          return <React.Fragment key={i}>{elem}</React.Fragment>
        }
      })
    } else {
      const trimText = text.trim()
      if (/^※/.test(trimText)) {
        return (
          <TxtCap className={Utils['Ml-0']} style={{ display: 'block' }}>
            {trimText}
          </TxtCap>
        )
      } else {
        const resultArr = trimText.split('※')
        return resultArr.map((elemC, i) => {
          if (i === 0) {
            return <React.Fragment key={i}>{elemC}</React.Fragment>
          } else {
            return (
              <React.Fragment key={i}>
                <small>※</small>
                {elemC}
              </React.Fragment>
            )
          }
        })
      }
    }
  }

  useEffect(() => {
    console.log(device)
  })

  return (
    <li>
      <CardCustom href={linkPath()}>
        <CardImg>
          <CardLabel>{isNew() && <span>NEW</span>}</CardLabel>

          <figure>
            <img src={imgPath()} alt="" width="160" />
          </figure>
        </CardImg>

        <CardData>
          <div className="label">
            <Rank className={rankLabelClass()}>
              <svg
                width="16"
                height="17"
                viewBox="0 0 16 17"
                fill="none"
                xmlns="http://www.w3.org/2000/svg"
              >
                <path
                  fillRule="evenodd"
                  clipRule="evenodd"
                  d="M3.14299 11L2.69449 6.082L4.41899 7.3135L5.25899 7.914L5.83199 7.0545L7.99999 3.8025L10.168 7.0545L10.7405 7.914L11.581 7.3135L13.3055 6.082L12.857 11H3.14299ZM11 6.5L8 2L5 6.5L1.5 4L2.23 12H2.5H3.2345H12.7655H13.5H13.77L14.5 4L11 6.5Z"
                  fill="white"
                />
                <path
                  fillRule="evenodd"
                  clipRule="evenodd"
                  d="M12.583 14L3.41653 13.9955L3.32553 13H2.32153L2.42053 14.087C2.46553 14.6035 2.89803 15 3.41703 15H12.583C13.102 15 13.5345 14.6035 13.5795 14.087L13.6785 13H12.6745L12.583 14Z"
                  fill="white"
                />
              </svg>
              <span>{device['rank-this-month']}</span>位
            </Rank>
            {!isNew() && (
              <Trend className={trendClass()}>
                {(() => {
                  if (trendText() === 'UP') {
                    return <IconArrowUp />
                  } else if (trendText() === 'Down') {
                    return <IconArrowDown />
                  } else {
                    return <IconArrowRight />
                  }
                })()}
                {trendText()}
              </Trend>
            )}
          </div>

          <Heading level="2" className={Utils['Mt-8']}>
            {device.product}
          </Heading>
          <div className="sub">
            <div>{device.manufacturer}</div>
            <TxtCap as="div" className={Utils['Ml-16']}>
              発売日:{displayRereaseDate()}
            </TxtCap>
          </div>

          <div className="price">
            {/* Appleの場合 */}
            {isApple() ? (
              <>
                <dl className="item">
                  <dt>48回払い（税込）</dt>
                  <TxtEmp01 as="dd">
                    月々<PriceNum>{displayPayment48()}</PriceNum>円～
                  </TxtEmp01>
                </dl>
                {isPayment48Note() && (
                  <p className="cap">
                    {device['payment48-text']}
                    {device['ranking-iphone-note1']}
                  </p>
                )}
                <dl className="item">
                  <dt>一括払い（税込）</dt>
                  {isDiscount() ? (
                    <dd>
                      <del>{displayPayment1()}円</del>→
                      <TxtNormal>
                        <TxtEmp01>{displayDiscount()}</TxtEmp01>
                      </TxtNormal>
                      円～
                    </dd>
                  ) : (
                    <dd>
                      <TxtNormal>
                        <TxtEmp01>{displayPayment1()}</TxtEmp01>
                      </TxtNormal>
                      円～
                    </dd>
                  )}
                </dl>
              </>
            ) : (
              <>
                {/* Rakutenオリジナル・Androidの場合 */}
                <dl className="item">
                  <dt>製品価格（税込）</dt>
                  <TxtEmp01 as="dd">
                    {isCancellation() && (
                      <TxtSizeWeightNormal size="s">
                        <span style={{ textDecoration: 'line-through' }}>
                          {displayCancellationPrice()}円
                        </span>{' '}
                        →
                      </TxtSizeWeightNormal>
                    )}
                    <PriceNum>{displayPrice()}</PriceNum>円
                  </TxtEmp01>
                </dl>
                {isPointBack1() && (
                  <dl className="item">
                    <dt style={{ fontSize: '12px' }}>
                      <TxtEmp02>
                        {device['pointback-pre-text1']}
                        <span style={{ fontSize: '17px' }}>
                          {displayPointBackPoint1()}
                        </span>
                        ポイント{device['pointback-post-text1']}
                        {device['ranking-note1']}
                      </TxtEmp02>
                    </dt>
                    <dd>
                      <TxtEmp02>
                        <PriceNum>-{displayPointBackPoint1()}</PriceNum>pt
                      </TxtEmp02>
                    </dd>
                  </dl>
                )}
                {isPointBack2() && (
                  <dl className="item">
                    <dt style={{ fontSize: '12px' }}>
                      <TxtEmp02>
                        {device['pointback-pre-text2']}
                        <span style={{ fontSize: '17px' }}>
                          {displayPointBackPoint2()}
                        </span>
                        ポイント{device['pointback-post-text2']}
                        {device['ranking-note2']}
                      </TxtEmp02>
                    </dt>
                    <dd>
                      <TxtEmp02>
                        <PriceNum>-{displayPointBackPoint2()}</PriceNum>pt
                      </TxtEmp02>
                    </dd>
                  </dl>
                )}
              </>
            )}
            <div className="result">
              {/* <!-- Appleの場合(計算結果) --> */}
              {isApple() ? (
                <TxtEmp02 as="div">
                  {device['top-carousel-iphone-pre-text']}
                  {device['top-carousel-iphone-pre-text2']}
                  {device['top-carousel-pointback-txt2']}
                  <PriceNum>{displayPointBackPointIphone()}</PriceNum>
                  {device['top-carousel-pointback-txt3']}
                  {device['ranking-iphone-note2']}
                </TxtEmp02>
              ) : (
                <TxtSize size="s" as="div">
                  {/* Rakutenオリジナル・Androidの場合(計算結果) */}
                  <TxtEmp01>
                    実質<PriceNum>{displayResultPrice()}</PriceNum>円
                  </TxtEmp01>
                </TxtSize>
              )}
              {isPointBack3() && (
                <TxtSize size="s" as="div">
                  <TxtEmp02>
                    {device['pointback-pre-text3']}
                    <span className="product-ranking-Card_Price-num">
                      {displayPointBackPoint3()}
                    </span>
                    ポイント{device['pointback-post-text3']}
                    {device['ranking-note3']}
                  </TxtEmp02>
                </TxtSize>
              )}
            </div>
          </div>
        </CardData>

        <CardFeature>
          <Heading level="4">特長</Heading>

          <UlOnly>
            <li className={Utils['Mt-8']}>
              {brInlistTransform(device.feature1)}
            </li>
            <li className={Utils['Mt-8']}>
              {brInlistTransform(device.feature2)}
            </li>
            <li className={Utils['Mt-8']}>
              {brInlistTransform(device.feature3)}
            </li>
          </UlOnly>

          <div className={Utils['Mt-16']}>
            {noteList().map((elem, i) => (
              <TxtCap key={i} as="p">
                {elem.trim()}
              </TxtCap>
            ))}
          </div>
        </CardFeature>
      </CardCustom>
    </li>
  )
}
