// AutoLoc/Project_Files/RMI/Source_Code_Samples/components/include/service/replacement-program/productlist/IphoneList.tsx
import React from 'react'
import { DeviceIphone } from '@components/include/common/ProductType'
import { device_iphone } from '~/js/csv-data/device-iphone'
import { IphoneCard } from '@components/include/service/replacement-program/productlist/IphoneCard'
import { ProductItemWrap } from '@components/include/service/replacement-program/productlist/Styles'

type Props = {
  className?: string
}

// A component for importing device_iphone.js (device_iphone.csv) and passing it to the card component for display in a list.
export const IphoneList: React.FC<Props> = ({ className }) => {
  const rawData: DeviceIphone[] = [...device_iphone]
  return (
    <ProductItemWrap className={className}>
      {rawData.map(data => {
        return <IphoneCard key={data.directory?.trim()} item={data} />
      })}
    </ProductItemWrap>
  )
}

// AutoLoc/Project_Files/RMI/Source_Code_Samples/vue/service/replacement-program/IphoneList.vue
<template>
    <ul class="service-replacement-program-Card">
        <Product
            v-for="(device, i) in iphoneData"
            :key="i"
            :summary="device"
        />
    </ul>
</template>

<script>
import Product from './iphone/Product.vue'
import { device_iphone } from '../../../js/csv-data/device-iphone'

export default {
    name: 'IphoneList',
    components: { Product },
    data() {
        return {
            iphoneData: [],
        }
    },
    created() {
        this.iphoneData = device_iphone;
    }
}
</script>
